# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 00:36
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='job_functions',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
