# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20160729_2305'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='sourceSite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='links.JobBoard', verbose_name='Source'),
        ),
    ]
