# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160807_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='job_fuction',
            new_name='job_function',
        ),
    ]
