# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160807_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='area_of_focus',
            field=models.CharField(blank=True, default=b'', max_length=500),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='employment_type',
            field=models.CharField(blank=True, default=b'', max_length=250),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_function',
            field=models.CharField(blank=True, default=b'', max_length=500),
        ),
    ]
