# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebLinkAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('local_url_data', models.CharField(max_length=128, verbose_name='Account')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.Company', verbose_name='Company')),
                ('company_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.CompanyLocation', verbose_name='Company Location')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.Contact', verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'Web Link Account',
                'verbose_name_plural': 'Web Link Accounts',
            },
        ),
        migrations.CreateModel(
            name='WebLinkType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Note')),
                ('base_url', models.URLField(blank=True, null=True, verbose_name=b'Base URL')),
            ],
            options={
                'verbose_name': 'Web Link Type',
                'verbose_name_plural': 'Web Link Types',
            },
        ),
        migrations.AddField(
            model_name='weblinkaccount',
            name='web_link_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.WebLinkType'),
        ),
    ]
