# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBoard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Job Board',
                'verbose_name_plural': 'Job Boards',
            },
        ),
    ]
