# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_jobboard_last_click'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobboard',
            options={'ordering': ['name'], 'verbose_name': 'Job Board', 'verbose_name_plural': 'Job Boards'},
        ),
        migrations.AddField(
            model_name='jobboard',
            name='url_regex',
            field=models.CharField(blank=True, default=b'', max_length=180, verbose_name='URL Regex'),
        ),
    ]
